#!/usr/bin/env python3
"""Encode Wsnow's MIT-licensed vintage PNG masks as textures and JS masks.

Uses only the standard library; assets are generated ahead of time, not at startup.
Preserves the source silhouettes and applies the X11 color 'snow' (#fffafa).
"""
import json
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parents[1]


def read_mask(path):
    """Read the bundled 1-bit grayscale PNGs without an imaging dependency.

    Deliberately accepts only Wsnow's source format: non-interlaced grayscale,
    one bit per pixel, black transparent. All five PNG row filters are handled.
    """
    data = path.read_bytes()
    if data[:8] != b'\x89PNG\r\n\x1a\n':
        raise ValueError(f'{path}: not a PNG')
    offset, chunks = 8, {}
    while offset < len(data):
        length = struct.unpack_from('!I', data, offset)[0]
        kind = data[offset + 4:offset + 8]
        payload = data[offset + 8:offset + 8 + length]
        checksum = struct.unpack_from('!I', data, offset + 8 + length)[0]
        if zlib.crc32(kind + payload) != checksum:
            raise ValueError(f'{path}: invalid PNG checksum')
        chunks.setdefault(kind, []).append(payload)
        offset += length + 12
    width, height, depth, color, compression, filtering, interlace = struct.unpack('!2I5B', chunks[b'IHDR'][0])
    if (depth, color, compression, filtering, interlace) != (1, 0, 0, 0, 0) or chunks.get(b'tRNS') != [b'\0\0']:
        raise ValueError(f'{path}: expected Wsnow 1-bit grayscale PNG with transparent black')
    stride = (width + 7) // 8
    raw = zlib.decompress(b''.join(chunks[b'IDAT']))
    if len(raw) != height * (stride + 1):
        raise ValueError(f'{path}: unexpected PNG data size')
    previous, rows = bytearray(stride), []
    for y in range(height):
        start = y * (stride + 1)
        method = raw[start]
        if method > 4:
            raise ValueError(f'{path}: unknown PNG filter')
        row = bytearray(raw[start + 1:start + 1 + stride])
        for x in range(stride):
            left = row[x - 1] if x else 0
            above = previous[x]
            upper_left = previous[x - 1] if x else 0
            prediction = left + above - upper_left
            paeth = min((left, above, upper_left), key=lambda value: abs(prediction - value))
            predictor = (0, left, above, (left + above) // 2, paeth)[method]
            row[x] = (row[x] + predictor) & 255
        rows.append(''.join('.' if row[x // 8] & (128 >> (x % 8)) else ' ' for x in range(width)))
        previous = row
    return rows


def png(rows):
    def chunk(kind, data):
        return struct.pack('!I', len(data)) + kind + data + struct.pack('!I', zlib.crc32(kind + data))
    width, height = len(rows[0]), len(rows)
    pixels = b''.join(b'\0' + b''.join(b'\xff\xfa\xfa\xff' if c == '.' else b'\0\0\0\0' for c in row) for row in rows)
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('!2I5B', width, height, 8, 6, 0, 0, 0))
            + chunk(b'IDAT', zlib.compress(pixels, 9)) + chunk(b'IEND', b''))


if __name__ == '__main__':
    masks = []
    for index in range(7):
        rows = read_mask(ROOT / 'assets' / 'wsnow' / f'snow{index:02d}.png')
        (ROOT / 'assets' / f'flake{index}.png').write_bytes(png(rows))
        masks.append(rows)
    (ROOT / 'Flakes.js').write_text('// Generated by tools/build_flakes.py from Wsnow 0.92. SPDX-License-Identifier: MIT\n'
                                  '// Copyright (c) 2020 Willem Vermin; see assets/wsnow/README.md.\n'
                                  + 'var masks = ' + json.dumps(masks, indent=4) + ';\n')
